### ISSUE TITLE
Usage of deprecated 'set' constructor

### ISSUE THREAD

**Issue by fsavigny** [dart-lang/rules_dart#169]
With bazel 0.9.0, I'm getting the following error message:

```
Traceback (most recent call last):
        File "/home/fsavigny/monorepo/lawlink/assets/scripts/BUILD.bazel", line 6
                dart_library(name = 'search')
        File "/home/fsavigny/.cache/bazel/_bazel_fsavigny/89bdeafc0083cf4d279498527fff7282/external/io_bazel_rules_dart/dart/build_rules/internal/dart_library.bzl", line 24, in dart_library_impl
                summary_action(ctx, dart_ctx)
        File "/home/fsavigny/.cache/bazel/_bazel_fsavigny/89bdeafc0083cf4d279498527fff7282/external/io_bazel_rules_dart/dart/build_rules/internal/analyze.bzl", line 222, in summary_action
                analyze_action(ctx, dart_ctx, summary = dart_ctx.st..., <2 more arguments>)
        File "/home/fsavigny/.cache/bazel/_bazel_fsavigny/89bdeafc0083cf4d279498527fff7282/external/io_bazel_rules_dart/dart/build_rules/internal/analyze.bzl", line 60, in analyze_action
                set
The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
```

Unfortunately, using the suggested command line argument yields the same error message.

**Comment by jakemac53** [comment]
Note that we don't plan on publishing 0.5.0 yet, so you will need to reference the sha directly to get the update for now.

If using `dazel` the init command supports a `--rules-commit=<sha>` flag to do this. The sha you want is `81f013e06291aa23454f6cd16eb1cba22c348508`.

**Comment by fsavigny** [comment]
Wow, that was fast. Thank you!
